# Generated by Django 5.2.5 on 2025-09-08 14:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('recipient_name', models.CharField(max_length=100)),
                ('certificate_text', models.TextField(blank=True, max_length=300)),
                ('signature_text', models.CharField(blank=True, max_length=100)),
                ('tree_count', models.PositiveIntegerField(default=1)),
                ('design', models.CharField(choices=[('professional', 'Professional'), ('modern', 'Modern'), ('elegant', 'Elegant')], default='professional', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('KZT', 'Kazakhstan Tenge'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('RUB', 'Russian Ruble')], default='KZT', max_length=3)),
                ('payment_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.CharField(choices=[('professional', 'Professional'), ('modern', 'Modern'), ('elegant', 'Elegant')], max_length=20, unique=True)),
                ('background_image', models.ImageField(upload_to='certificate_templates/')),
            ],
        ),
    ]
