# Generated by Django 5.2.5 on 2025-09-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='variation',
            field=models.CharField(help_text="Variation name, e.g., 'variation-1'", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='design',
            field=models.CharField(choices=[('professional', 'Professional'), ('modern', 'Modern'), ('elegant', 'Elegant')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='certificatetemplate',
            unique_together={('design', 'variation')},
        ),
    ]
