# Generated by Django 5.2.5 on 2025-09-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_certificatetemplate_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificatetemplate',
            options={'ordering': ['design', 'variation']},
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='description',
            field=models.TextField(blank=True, help_text='Template description'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='name',
            field=models.CharField(blank=True, help_text='Template display mame', max_length=100),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='variation',
            field=models.CharField(default='default', help_text="Введите имя сертификата, например: 'v1'", max_length=50),
        ),
    ]
