# Generated by Django 5.2.5 on 2025-09-13 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_certificatetemplate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.certificatetemplate'),
        ),
    ]
