# Generated by Django 5.2.5 on 2025-10-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_certificate_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetemplate',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='certificate_templates/'),
        ),
    ]
