# Generated by Django 5.2.5 on 2025-10-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_certificatetemplate_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetemplate',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Upload certificate template background image', null=True, upload_to='certificate_templates/'),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='name',
            field=models.CharField(blank=True, help_text='Template display name', max_length=100),
        ),
    ]
