# Generated by Django 5.2.5 on 2025-10-29 10:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_certificatetemplate_background_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('organization', models.CharField(blank=True, max_length=150)),
                ('region', models.CharField(max_length=50)),
                ('plan', models.TextField()),
                ('submitted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('region', models.CharField(max_length=50)),
                ('dates', models.CharField(blank=True, max_length=200)),
                ('experience', models.TextField(blank=True)),
                ('submitted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
