# Generated by Django 5.2.5 on 2025-10-30 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_certificate_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=20, unique=True)),
                ('phone_verified', models.BooleanField(default=False)),
                ('total_trees_planted', models.IntegerField(default=0)),
                ('total_donations', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('preferred_language', models.CharField(choices=[('ru', 'Russian'), ('kz', 'Kazakh'), ('en', 'English')], default='ru', max_length=2)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='certificate',
            name='customer_phone',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['customer_phone', 'created_at'], name='main_app_ce_custome_53db0b_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['customer_email', 'created_at'], name='main_app_ce_custome_8d61cf_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['user', 'created_at'], name='main_app_ce_user_id_493811_idx'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['phone_number'], name='main_app_us_phone_n_e1da0a_idx'),
        ),
    ]
